INSERT INTO images (id, url, description) VALUES
    ('40000000-0000-0000-0000-000000000001', 'C:\Users\sladk\Downloads\triplify\ui\src\main\resources\com\triplify\ui\pages\trips\images\default.png', null);


CREATE TEMP TABLE tmp_seed_places (
    country_name TEXT NOT NULL,
    place_order INTEGER NOT NULL,
    title_en TEXT NOT NULL,
    description_en TEXT NOT NULL
);

INSERT INTO tmp_seed_places (country_name, place_order, title_en, description_en) VALUES
    ('Portugal', 1, 'Portugal - Alfama District #01', 'One of the most visited spots in Portugal, popular for alfama district.'),
    ('Portugal', 2, 'Portugal - Belem Tower #02', 'A memorable location in Portugal that travelers choose for belem tower.'),
    ('Portugal', 3, 'Portugal - Jeronimos Monastery #03', 'A signature place in Portugal, often recommended for jeronimos monastery.'),
    ('Portugal', 4, 'Portugal - Ribeira Waterfront #04', 'A landmark stop in Portugal known for ribeira waterfront.'),
    ('Portugal', 5, 'Portugal - Livraria Lello #05', 'One of the most visited spots in Portugal, popular for livraria lello.'),
    ('Portugal', 6, 'Portugal - Pena Palace #06', 'A memorable location in Portugal that travelers choose for pena palace.'),
    ('Portugal', 7, 'Portugal - Quinta da Regaleira #07', 'A signature place in Portugal, often recommended for quinta da regaleira.'),
    ('Portugal', 8, 'Portugal - Douro Valley Viewpoint #08', 'A landmark stop in Portugal known for douro valley viewpoint.'),
    ('Portugal', 9, 'Portugal - Nazare Cliffs #09', 'One of the most visited spots in Portugal, popular for nazare cliffs.'),
    ('Portugal', 10, 'Portugal - Obidos Castle Walls #10', 'A memorable location in Portugal that travelers choose for obidos castle walls.'),
    ('Portugal', 11, 'Portugal - Porto Sao Bento #11', 'A signature place in Portugal, often recommended for porto sao bento.'),
    ('Portugal', 12, 'Portugal - Evora Roman Temple #12', 'A landmark stop in Portugal known for evora roman temple.'),
    ('Portugal', 13, 'Portugal - Coimbra University Courtyard #13', 'One of the most visited spots in Portugal, popular for coimbra university courtyard.'),
    ('Portugal', 14, 'Portugal - Aveiro Canals #14', 'A memorable location in Portugal that travelers choose for aveiro canals.'),
    ('Portugal', 15, 'Portugal - Cascais Marina #15', 'A signature place in Portugal, often recommended for cascais marina.'),
    ('Portugal', 16, 'Portugal - Sintra Old Town #16', 'A landmark stop in Portugal known for sintra old town.'),
    ('Portugal', 17, 'Portugal - Ponta da Piedade #17', 'One of the most visited spots in Portugal, popular for ponta da piedade.'),
    ('Portugal', 18, 'Portugal - Madeira Monte Palace #18', 'A memorable location in Portugal that travelers choose for madeira monte palace.'),
    ('Portugal', 19, 'Portugal - Bom Jesus do Monte #19', 'A signature place in Portugal, often recommended for bom jesus do monte.'),
    ('Portugal', 20, 'Portugal - Guimaraes Castle #20', 'A landmark stop in Portugal known for guimaraes castle.'),
    ('Spain', 1, 'Spain - Sagrada Familia #01', 'One of the most visited spots in Spain, popular for sagrada familia.'),
    ('Spain', 2, 'Spain - Park Guell #02', 'A memorable location in Spain that travelers choose for park guell.'),
    ('Spain', 3, 'Spain - Alhambra #03', 'A signature place in Spain, often recommended for alhambra.'),
    ('Spain', 4, 'Spain - Plaza Mayor Madrid #04', 'A landmark stop in Spain known for plaza mayor madrid.'),
    ('Spain', 5, 'Spain - Royal Alcazar Seville #05', 'One of the most visited spots in Spain, popular for royal alcazar seville.'),
    ('Spain', 6, 'Spain - City of Arts and Sciences #06', 'A memorable location in Spain that travelers choose for city of arts and sciences.'),
    ('Spain', 7, 'Spain - Toledo Old Town #07', 'A signature place in Spain, often recommended for toledo old town.'),
    ('Spain', 8, 'Spain - Santiago Cathedral #08', 'A landmark stop in Spain known for santiago cathedral.'),
    ('Spain', 9, 'Spain - Guggenheim Bilbao #09', 'One of the most visited spots in Spain, popular for guggenheim bilbao.'),
    ('Spain', 10, 'Spain - Puente Nuevo Ronda #10', 'A memorable location in Spain that travelers choose for puente nuevo ronda.'),
    ('Spain', 11, 'Spain - Mezquita of Cordoba #11', 'A signature place in Spain, often recommended for mezquita of cordoba.'),
    ('Spain', 12, 'Spain - Segovia Aqueduct #12', 'A landmark stop in Spain known for segovia aqueduct.'),
    ('Spain', 13, 'Spain - Costa Brava Coves #13', 'One of the most visited spots in Spain, popular for costa brava coves.'),
    ('Spain', 14, 'Spain - Dalt Vila Ibiza #14', 'A memorable location in Spain that travelers choose for dalt vila ibiza.'),
    ('Spain', 15, 'Spain - Montserrat Monastery #15', 'A signature place in Spain, often recommended for montserrat monastery.'),
    ('Spain', 16, 'Spain - La Concha Bay #16', 'A landmark stop in Spain known for la concha bay.'),
    ('Spain', 17, 'Spain - Camino Frances Stretch #17', 'One of the most visited spots in Spain, popular for camino frances stretch.'),
    ('Spain', 18, 'Spain - Malaga Alcazaba #18', 'A memorable location in Spain that travelers choose for malaga alcazaba.'),
    ('Spain', 19, 'Spain - Salamanca Plaza Mayor #19', 'A signature place in Spain, often recommended for salamanca plaza mayor.'),
    ('Spain', 20, 'Spain - Girona Jewish Quarter #20', 'A landmark stop in Spain known for girona jewish quarter.'),
    ('France', 1, 'France - Montmartre Steps #01', 'One of the most visited spots in France, popular for montmartre steps.'),
    ('France', 2, 'France - Louvre Courtyard #02', 'A memorable location in France that travelers choose for louvre courtyard.'),
    ('France', 3, 'France - Eiffel Trocadero #03', 'A signature place in France, often recommended for eiffel trocadero.'),
    ('France', 4, 'France - Versailles Gardens #04', 'A landmark stop in France known for versailles gardens.'),
    ('France', 5, 'France - Annecy Old Canals #05', 'One of the most visited spots in France, popular for annecy old canals.'),
    ('France', 6, 'France - Carcassonne Citadel #06', 'A memorable location in France that travelers choose for carcassonne citadel.'),
    ('France', 7, 'France - Nice Promenade des Anglais #07', 'A signature place in France, often recommended for nice promenade des anglais.'),
    ('France', 8, 'France - Lyon Old Town #08', 'A landmark stop in France known for lyon old town.'),
    ('France', 9, 'France - Bordeaux Mirror Pool #09', 'One of the most visited spots in France, popular for bordeaux mirror pool.'),
    ('France', 10, 'France - Avignon Palace of Popes #10', 'A memorable location in France that travelers choose for avignon palace of popes.'),
    ('France', 11, 'France - Etretat Cliffs #11', 'A signature place in France, often recommended for etretat cliffs.'),
    ('France', 12, 'France - Colmar Little Venice #12', 'A landmark stop in France known for colmar little venice.'),
    ('France', 13, 'France - Saint-Malo Ramparts #13', 'One of the most visited spots in France, popular for saint-malo ramparts.'),
    ('France', 14, 'France - Loire Chateau Chambord #14', 'A memorable location in France that travelers choose for loire chateau chambord.'),
    ('France', 15, 'France - Arles Roman Arena #15', 'A signature place in France, often recommended for arles roman arena.'),
    ('France', 16, 'France - Chamonix Valley Walk #16', 'A landmark stop in France known for chamonix valley walk.'),
    ('France', 17, 'France - Nimes Maison Carree #17', 'One of the most visited spots in France, popular for nimes maison carree.'),
    ('France', 18, 'France - Aix Cours Mirabeau #18', 'A memorable location in France that travelers choose for aix cours mirabeau.'),
    ('France', 19, 'France - Rocamadour Sanctuary #19', 'A signature place in France, often recommended for rocamadour sanctuary.'),
    ('France', 20, 'France - Strasbourg Petite France #20', 'A landmark stop in France known for strasbourg petite france.'),
    ('Italy', 1, 'Italy - Trastevere Lanes #01', 'One of the most visited spots in Italy, popular for trastevere lanes.'),
    ('Italy', 2, 'Italy - Ponte Vecchio #02', 'A memorable location in Italy that travelers choose for ponte vecchio.'),
    ('Italy', 3, 'Italy - Duomo di Milano #03', 'A signature place in Italy, often recommended for duomo di milano.'),
    ('Italy', 4, 'Italy - Colosseum Forum Edge #04', 'A landmark stop in Italy known for colosseum forum edge.'),
    ('Italy', 5, 'Italy - Cinque Terre Vernazza #05', 'One of the most visited spots in Italy, popular for cinque terre vernazza.'),
    ('Italy', 6, 'Italy - Amalfi Cathedral Steps #06', 'A memorable location in Italy that travelers choose for amalfi cathedral steps.'),
    ('Italy', 7, 'Italy - Lake Como Bellagio #07', 'A signature place in Italy, often recommended for lake como bellagio.'),
    ('Italy', 8, 'Italy - Siena Piazza del Campo #08', 'A landmark stop in Italy known for siena piazza del campo.'),
    ('Italy', 9, 'Italy - Matera Sassi Quarter #09', 'One of the most visited spots in Italy, popular for matera sassi quarter.'),
    ('Italy', 10, 'Italy - Bologna Porticoes #10', 'A memorable location in Italy that travelers choose for bologna porticoes.'),
    ('Italy', 11, 'Italy - Verona Arena #11', 'A signature place in Italy, often recommended for verona arena.'),
    ('Italy', 12, 'Italy - Pompeii Ruins #12', 'A landmark stop in Italy known for pompeii ruins.'),
    ('Italy', 13, 'Italy - Turin Mole Antonelliana #13', 'One of the most visited spots in Italy, popular for turin mole antonelliana.'),
    ('Italy', 14, 'Italy - Orvieto Funicular Gate #14', 'A memorable location in Italy that travelers choose for orvieto funicular gate.'),
    ('Italy', 15, 'Italy - Perugia Rocca Paolina #15', 'A signature place in Italy, often recommended for perugia rocca paolina.'),
    ('Italy', 16, 'Italy - Ravenna Mosaics #16', 'A landmark stop in Italy known for ravenna mosaics.'),
    ('Italy', 17, 'Italy - Capri Gardens of Augustus #17', 'One of the most visited spots in Italy, popular for capri gardens of augustus.'),
    ('Italy', 18, 'Italy - Lecce Baroque Center #18', 'A memorable location in Italy that travelers choose for lecce baroque center.'),
    ('Italy', 19, 'Italy - Trieste Canal Grande #19', 'A signature place in Italy, often recommended for trieste canal grande.'),
    ('Italy', 20, 'Italy - Palermo Ballaro Market #20', 'A landmark stop in Italy known for palermo ballaro market.'),
    ('Germany', 1, 'Germany - Brandenburg Gate #01', 'One of the most visited spots in Germany, popular for brandenburg gate.'),
    ('Germany', 2, 'Germany - Neuschwanstein Overlook #02', 'A memorable location in Germany that travelers choose for neuschwanstein overlook.'),
    ('Germany', 3, 'Germany - Cologne Cathedral Square #03', 'A signature place in Germany, often recommended for cologne cathedral square.'),
    ('Germany', 4, 'Germany - Heidelberg Castle Terrace #04', 'A landmark stop in Germany known for heidelberg castle terrace.'),
    ('Germany', 5, 'Germany - Rothenburg Walls #05', 'One of the most visited spots in Germany, popular for rothenburg walls.'),
    ('Germany', 6, 'Germany - Hamburg Speicherstadt #06', 'A memorable location in Germany that travelers choose for hamburg speicherstadt.'),
    ('Germany', 7, 'Germany - Dresden Zwinger #07', 'A signature place in Germany, often recommended for dresden zwinger.'),
    ('Germany', 8, 'Germany - Black Forest Triberg #08', 'A landmark stop in Germany known for black forest triberg.'),
    ('Germany', 9, 'Germany - Munich Marienplatz #09', 'One of the most visited spots in Germany, popular for munich marienplatz.'),
    ('Germany', 10, 'Germany - Nuremberg Castle Yard #10', 'A memorable location in Germany that travelers choose for nuremberg castle yard.'),
    ('Germany', 11, 'Germany - Bamberg Old Town #11', 'A signature place in Germany, often recommended for bamberg old town.'),
    ('Germany', 12, 'Germany - Leipzig Thomaskirche Area #12', 'A landmark stop in Germany known for leipzig thomaskirche.'),
    ('Germany', 13, 'Germany - Potsdam Sanssouci #13', 'One of the most visited spots in Germany, popular for potsdam sanssouci.'),
    ('Germany', 14, 'Germany - Saxon Switzerland Bastei #14', 'A memorable location in Germany that travelers choose for saxon switzerland bastei.'),
    ('Germany', 15, 'Germany - Moselle Cochem Promenade #15', 'A signature place in Germany, often recommended for moselle cochem promenade.'),
    ('Germany', 16, 'Germany - Frankfurt Romerberg #16', 'A landmark stop in Germany known for frankfurt romerberg.'),
    ('Germany', 17, 'Germany - Freiburg Minster Square #17', 'One of the most visited spots in Germany, popular for freiburg minster square.'),
    ('Germany', 18, 'Germany - Lubeck Holsten Gate #18', 'A memorable location in Germany that travelers choose for lubeck holsten gate.'),
    ('Germany', 19, 'Germany - Wurzburg Residence Garden #19', 'A signature place in Germany, often recommended for wurzburg residence garden.'),
    ('Germany', 20, 'Germany - Berchtesgaden Eagle View #20', 'A landmark stop in Germany known for berchtesgaden eagle view.'),
    ('Japan', 1, 'Japan - Fushimi Inari Trail #01', 'One of the most visited spots in Japan, popular for fushimi inari trail.'),
    ('Japan', 2, 'Japan - Asakusa Senso-ji #02', 'A memorable location in Japan that travelers choose for asakusa senso-ji.'),
    ('Japan', 3, 'Japan - Shibuya Scramble #03', 'A signature place in Japan, often recommended for shibuya scramble.'),
    ('Japan', 4, 'Japan - Arashiyama Bamboo Grove #04', 'A landmark stop in Japan known for arashiyama bamboo grove.'),
    ('Japan', 5, 'Japan - Himeji Castle #05', 'One of the most visited spots in Japan, popular for himeji castle.'),
    ('Japan', 6, 'Japan - Nara Deer Park #06', 'A memorable location in Japan that travelers choose for nara deer park.'),
    ('Japan', 7, 'Japan - Kanazawa Kenrokuen #07', 'A signature place in Japan, often recommended for kanazawa kenrokuen.'),
    ('Japan', 8, 'Japan - Miyajima Floating Gate #08', 'A landmark stop in Japan known for miyajima floating gate.'),
    ('Japan', 9, 'Japan - Hakone Lake Ashi #09', 'One of the most visited spots in Japan, popular for hakone lake ashi.'),
    ('Japan', 10, 'Japan - Nikko Toshogu #10', 'A memorable location in Japan that travelers choose for nikko toshogu.'),
    ('Japan', 11, 'Japan - Kamakura Great Buddha #11', 'A signature place in Japan, often recommended for kamakura great buddha.'),
    ('Japan', 12, 'Japan - Osaka Dotonbori #12', 'A landmark stop in Japan known for osaka dotonbori.'),
    ('Japan', 13, 'Japan - Takayama Old Streets #13', 'One of the most visited spots in Japan, popular for takayama old streets.'),
    ('Japan', 14, 'Japan - Kobe Harborland #14', 'A memorable location in Japan that travelers choose for kobe harborland.'),
    ('Japan', 15, 'Japan - Nagasaki Glover Garden #15', 'A signature place in Japan, often recommended for nagasaki glover garden.'),
    ('Japan', 16, 'Japan - Sapporo Odori Park #16', 'A landmark stop in Japan known for sapporo odori park.'),
    ('Japan', 17, 'Japan - Aomori Nebuta Museum #17', 'One of the most visited spots in Japan, popular for aomori nebuta museum.'),
    ('Japan', 18, 'Japan - Koyasan Okunoin #18', 'A memorable location in Japan that travelers choose for koyasan okunoin.'),
    ('Japan', 19, 'Japan - Beppu Steam District #19', 'A signature place in Japan, often recommended for beppu steam district.'),
    ('Japan', 20, 'Japan - Okinawa Shuri Castle #20', 'A landmark stop in Japan known for okinawa shuri castle.'),
    ('Thailand', 1, 'Thailand - Chiang Mai Old City #01', 'One of the most visited spots in Thailand, popular for chiang mai old city.'),
    ('Thailand', 2, 'Thailand - Grand Palace Bangkok #02', 'A memorable location in Thailand that travelers choose for grand palace bangkok.'),
    ('Thailand', 3, 'Thailand - Wat Arun Riverside #03', 'A signature place in Thailand, often recommended for wat arun riverside.'),
    ('Thailand', 4, 'Thailand - Ayutthaya Historical Park #04', 'A landmark stop in Thailand known for ayutthaya historical park.'),
    ('Thailand', 5, 'Thailand - Pai Canyon #05', 'One of the most visited spots in Thailand, popular for pai canyon.'),
    ('Thailand', 6, 'Thailand - Phuket Old Town #06', 'A memorable location in Thailand that travelers choose for phuket old town.'),
    ('Thailand', 7, 'Thailand - Krabi Railay Beach #07', 'A signature place in Thailand, often recommended for krabi railay beach.'),
    ('Thailand', 8, 'Thailand - Sukhothai Ruins #08', 'A landmark stop in Thailand known for sukhothai ruins.'),
    ('Thailand', 9, 'Thailand - Kanchanaburi Bridge #09', 'One of the most visited spots in Thailand, popular for kanchanaburi bridge.'),
    ('Thailand', 10, 'Thailand - Khao Sok Lake Pier #10', 'A memorable location in Thailand that travelers choose for khao sok lake pier.'),
    ('Thailand', 11, 'Thailand - Koh Samui Fisherman Village #11', 'A signature place in Thailand, often recommended for koh samui fisherman village.'),
    ('Thailand', 12, 'Thailand - Koh Tao Viewpoint #12', 'A landmark stop in Thailand known for koh tao viewpoint.'),
    ('Thailand', 13, 'Thailand - Hua Hin Night Market #13', 'One of the most visited spots in Thailand, popular for hua hin night market.'),
    ('Thailand', 14, 'Thailand - Lampang Horse Carriage Quarter #14', 'A memorable location in Thailand that travelers choose for lampang horse carriage quarter.'),
    ('Thailand', 15, 'Thailand - Trat Mangrove Walk #15', 'A signature place in Thailand, often recommended for trat mangrove walk.'),
    ('Thailand', 16, 'Thailand - Udon Thani Red Lotus Lake #16', 'A landmark stop in Thailand known for udon thani red lotus lake.'),
    ('Thailand', 17, 'Thailand - Pattaya Sanctuary of Truth #17', 'One of the most visited spots in Thailand, popular for pattaya sanctuary of truth.'),
    ('Thailand', 18, 'Thailand - Mae Hong Son Loop Stop #18', 'A memorable location in Thailand that travelers choose for mae hong son loop stop.'),
    ('Thailand', 19, 'Thailand - Phang Nga Bay Pier #19', 'A signature place in Thailand, often recommended for phang nga bay pier.'),
    ('Thailand', 20, 'Thailand - Surat Thani Riverfront #20', 'A landmark stop in Thailand known for surat thani riverfront.'),
    ('Mexico', 1, 'Mexico - Chichen Itza Plaza #01', 'One of the most visited spots in Mexico, popular for chichen itza plaza.'),
    ('Mexico', 2, 'Mexico - Teotihuacan Avenue of the Dead #02', 'A memorable location in Mexico that travelers choose for teotihuacan avenue of the dead.'),
    ('Mexico', 3, 'Mexico - Zocalo Mexico City #03', 'A signature place in Mexico, often recommended for zocalo mexico city.'),
    ('Mexico', 4, 'Mexico - Guanajuato Alleyways #04', 'A landmark stop in Mexico known for guanajuato alleyways.'),
    ('Mexico', 5, 'Mexico - Oaxaca Santo Domingo #05', 'One of the most visited spots in Mexico, popular for oaxaca santo domingo.'),
    ('Mexico', 6, 'Mexico - Puebla Historic Center #06', 'A memorable location in Mexico that travelers choose for puebla historic center.'),
    ('Mexico', 7, 'Mexico - Merida Paseo Montejo #07', 'A signature place in Mexico, often recommended for merida paseo montejo.'),
    ('Mexico', 8, 'Mexico - Tulum Ruins Coast #08', 'A landmark stop in Mexico known for tulum ruins coast.'),
    ('Mexico', 9, 'Mexico - Bacalar Lagoon Deck #09', 'One of the most visited spots in Mexico, popular for bacalar lagoon deck.'),
    ('Mexico', 10, 'Mexico - San Miguel de Allende Parroquia #10', 'A memorable location in Mexico that travelers choose for san miguel de allende parroquia.'),
    ('Mexico', 11, 'Mexico - Copper Canyon Rim #11', 'A signature place in Mexico, often recommended for copper canyon rim.'),
    ('Mexico', 12, 'Mexico - Isla Mujeres Norte Beach #12', 'A landmark stop in Mexico known for isla mujeres norte beach.'),
    ('Mexico', 13, 'Mexico - Campeche Walled Streets #13', 'One of the most visited spots in Mexico, popular for campeche walled streets.'),
    ('Mexico', 14, 'Mexico - Queretaro Aqueduct Walk #14', 'A memorable location in Mexico that travelers choose for queretaro aqueduct walk.'),
    ('Mexico', 15, 'Mexico - Morelia Cathedral Plaza #15', 'A signature place in Mexico, often recommended for morelia cathedral plaza.'),
    ('Mexico', 16, 'Mexico - Veracruz Malecon #16', 'A landmark stop in Mexico known for veracruz malecon.'),
    ('Mexico', 17, 'Mexico - Holbox Sandbar #17', 'One of the most visited spots in Mexico, popular for holbox sandbar.'),
    ('Mexico', 18, 'Mexico - Cancun El Rey Site #18', 'A memorable location in Mexico that travelers choose for cancun el rey site.'),
    ('Mexico', 19, 'Mexico - Toluca Cosmovitral #19', 'A signature place in Mexico, often recommended for toluca cosmovitral.'),
    ('Mexico', 20, 'Mexico - Monterrey Santa Lucia Walk #20', 'A landmark stop in Mexico known for monterrey santa lucia walk.'),
    ('United States', 1, 'United States - Grand Canyon South Rim #01', 'One of the most visited spots in United States, popular for grand canyon south rim.'),
    ('United States', 2, 'United States - Golden Gate Bridge #02', 'A memorable location in United States that travelers choose for golden gate bridge.'),
    ('United States', 3, 'United States - Times Square Broadway Block #03', 'A signature place in United States, often recommended for times square broadway.'),
    ('United States', 4, 'United States - National Mall Reflecting Pool #04', 'A landmark stop in United States known for national mall reflecting pool.'),
    ('United States', 5, 'United States - French Quarter Jackson Square #05', 'One of the most visited spots in United States, popular for french quarter jackson square.'),
    ('United States', 6, 'United States - Chicago Riverwalk #06', 'A memorable location in United States that travelers choose for chicago riverwalk.'),
    ('United States', 7, 'United States - Yosemite Valley Floor #07', 'A signature place in United States, often recommended for yosemite valley floor.'),
    ('United States', 8, 'United States - Monument Valley Overlook #08', 'A landmark stop in United States known for monument valley overlook.'),
    ('United States', 9, 'United States - Antelope Canyon Entrance #09', 'One of the most visited spots in United States, popular for antelope canyon entrance.'),
    ('United States', 10, 'United States - Miami South Beach #10', 'A memorable location in United States that travelers choose for miami south beach.'),
    ('United States', 11, 'United States - Seattle Pike Place #11', 'A signature place in United States, often recommended for seattle pike place.'),
    ('United States', 12, 'United States - Boston Freedom Trail Segment #12', 'A landmark stop in United States known for boston freedom trail.'),
    ('United States', 13, 'United States - San Diego Balboa Park #13', 'One of the most visited spots in United States, popular for san diego balboa park.'),
    ('United States', 14, 'United States - Nashville Broadway Strip #14', 'A memorable location in United States that travelers choose for nashville broadway strip.'),
    ('United States', 15, 'United States - Charleston Battery #15', 'A signature place in United States, often recommended for charleston battery.'),
    ('United States', 16, 'United States - Sedona Cathedral Rock #16', 'A landmark stop in United States known for sedona cathedral rock.'),
    ('United States', 17, 'United States - Portland Waterfront Park #17', 'One of the most visited spots in United States, popular for portland waterfront park.'),
    ('United States', 18, 'United States - Austin South Congress #18', 'A memorable location in United States that travelers choose for austin south congress.'),
    ('United States', 19, 'United States - Philadelphia Old City #19', 'A signature place in United States, often recommended for philadelphia old city.'),
    ('United States', 20, 'United States - Savannah Forsyth Park #20', 'A landmark stop in United States known for savannah forsyth park.'),
    ('Australia', 1, 'Australia - Bondi Beachfront #01', 'One of the most visited spots in Australia, popular for bondi beachfront.'),
    ('Australia', 2, 'Australia - Great Ocean Road Lookout #02', 'A memorable location in Australia that travelers choose for great ocean road lookout.'),
    ('Australia', 3, 'Australia - Sydney Harbour Bridge Pylon #03', 'A signature place in Australia, often recommended for sydney harbour bridge pylon.'),
    ('Australia', 4, 'Australia - Melbourne Laneways Center #04', 'A landmark stop in Australia known for melbourne laneways center.'),
    ('Australia', 5, 'Australia - Uluru Sunset Viewing Area #05', 'One of the most visited spots in Australia, popular for uluru sunset viewing.'),
    ('Australia', 6, 'Australia - Blue Mountains Echo Point #06', 'A memorable location in Australia that travelers choose for blue mountains echo point.'),
    ('Australia', 7, 'Australia - Fremantle Cappuccino Strip #07', 'A signature place in Australia, often recommended for fremantle cappuccino strip.'),
    ('Australia', 8, 'Australia - Brisbane South Bank #08', 'A landmark stop in Australia known for brisbane south bank.'),
    ('Australia', 9, 'Australia - Adelaide Central Market #09', 'One of the most visited spots in Australia, popular for adelaide central market.'),
    ('Australia', 10, 'Australia - Hobart Salamanca Place #10', 'A memorable location in Australia that travelers choose for hobart salamanca place.'),
    ('Australia', 11, 'Australia - Cairns Esplanade Lagoon #11', 'A signature place in Australia, often recommended for cairns esplanade lagoon.'),
    ('Australia', 12, 'Australia - Byron Bay Lighthouse Path #12', 'A landmark stop in Australia known for byron bay lighthouse path.'),
    ('Australia', 13, 'Australia - Canberra Lake Burley Walk #13', 'One of the most visited spots in Australia, popular for canberra lake burley walk.'),
    ('Australia', 14, 'Australia - Kakadu Ubirr Lookout #14', 'A memorable location in Australia that travelers choose for kakadu ubirr lookout.'),
    ('Australia', 15, 'Australia - Noosa Main Beach #15', 'A signature place in Australia, often recommended for noosa main beach.'),
    ('Australia', 16, 'Australia - Darwin Waterfront Precinct #16', 'A landmark stop in Australia known for darwin waterfront precinct.'),
    ('Australia', 17, 'Australia - Margaret River Cellar Trail #17', 'One of the most visited spots in Australia, popular for margaret river cellar trail.'),
    ('Australia', 18, 'Australia - Launceston Cataract Gorge #18', 'A memorable location in Australia that travelers choose for launceston cataract gorge.'),
    ('Australia', 19, 'Australia - Gold Coast Burleigh Headland #19', 'A signature place in Australia, often recommended for gold coast burleigh headland.'),
    ('Australia', 20, 'Australia - Townsville The Strand #20', 'A landmark stop in Australia known for townsville the strand.');

INSERT OR IGNORE INTO places (
    id,
    user_id,
    country_id,
    cover_image_id,
    title,
    description,
    latitude,
    longitude
)
SELECT
    lower(
        hex(randomblob(4)) || '-' ||
        hex(randomblob(2)) || '-' ||
        '4' || substr(hex(randomblob(2)), 2) || '-' ||
        substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' ||
        hex(randomblob(6))
    ) AS id,
    'f1d1a33f-1e7c-4ea1-bb1d-c8f06efb5b5a' AS user_id,
    c.id AS country_id,
    '40000000-0000-0000-0000-000000000001' AS cover_image_id,
    p.title_en,
    (
        'The stop at ' || p.title_en || ' in ' || p.country_name || ' is designed as a full-day anchor rather than a quick checkbox visit. Start in the early morning with a slow orientation walk around the access streets so you can understand where transit points, pedestrian lanes, and quieter corners are located before peak visitor flow begins. Continue with two focused exploration blocks: first for signature architecture, panoramic viewpoints, and classic photo angles, then for neighborhood texture such as side lanes, local craft storefronts, and food counters where the area feels less staged and more lived-in. Keep a measured pace and avoid rushing transitions, because this stop is meant to be experienced in layers, not consumed in one pass. '
        || 'Plan a mid-day recovery window with shaded seating, water refill points, and one flexible meal break close to the central walking zone. In the afternoon, shift attention to spaces that become most atmospheric when crowds thin and light softens, including terraces, river edges, courtyards, or market streets depending on local layout. The route structure around this stop includes intentional buffer for queue delays, weather changes, and short detours, so small schedule adjustments do not break the rest of the day. If conditions are ideal, reserve an optional sunset loop followed by a final evening pass through the most walkable district segment before transfer. '
        || 'For seeded planning consistency, this record keeps practical timing assumptions while still leaving room for spontaneous choices and personal interests. Treat ' || p.title_en || ' as a complete destination in ' || p.country_name || ', not just a photo checkpoint, and the experience will feel richer, calmer, and noticeably more memorable from morning through late evening.'
    ) AS description,
    CASE
        WHEN p.place_order IN (1, 11) THEN 0.0
        ELSE round(cs.base_lat + (((RANDOM() % 1000000) / 1000000.0) * 2.0), 6)
        END AS latitude,
    CASE
        WHEN p.place_order IN (1, 11) THEN 0.0
        ELSE round(cs.base_lon + (((RANDOM() % 1000000) / 1000000.0) * 2.0), 6)
        END AS longitude
FROM tmp_seed_places p
INNER JOIN countries c
    ON c.name = p.country_name
INNER JOIN (
    SELECT 'Portugal' AS country_name, 39.40 AS base_lat, -8.20 AS base_lon
    UNION ALL SELECT 'Spain', 40.20, -3.70
    UNION ALL SELECT 'France', 46.20, 2.20
    UNION ALL SELECT 'Italy', 42.80, 12.50
    UNION ALL SELECT 'Germany', 51.00, 10.40
    UNION ALL SELECT 'Japan', 35.60, 139.30
    UNION ALL SELECT 'Thailand', 13.70, 100.50
    UNION ALL SELECT 'Mexico', 19.40, -99.10
    UNION ALL SELECT 'United States', 39.50, -98.30
    UNION ALL SELECT 'Australia', -33.80, 151.10
) cs
    ON cs.country_name = p.country_name;

DROP TABLE tmp_seed_places;
