package com.triplify.ui.shared.util;

import javafx.scene.image.Image;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.net.URI;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Collectors;

// Generated by Copilot (modified by us), fixes the problem with low resolution emojis in standard javafx
public final class EmojiUtil {

    private static final String RESOURCES_BASE = "/com/triplify/ui/emoji/";
    private static final String CDN = "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/";
    //TODO: Remove DISK_CACHE on release and move all the created emojis to BUNDLED_BASE
    private static final Path DISK_CACHE = Path.of(System.getProperty("user.home"), ".triplify", "emoji");
    private static final int MEMORY_CACHE_LIMIT = 512;

    private static final Map<String, Image> memCache = Collections.synchronizedMap(
            new LinkedHashMap<>(128, 0.75f, true) {
                @Override
                protected boolean removeEldestEntry(Map.Entry<String, Image> eldest) {
                    return size() > MEMORY_CACHE_LIMIT;
                }
            }
    );
    private static final Logger logger = LoggerFactory.getLogger(EmojiUtil.class);
    static {
        try {
            Files.createDirectories(DISK_CACHE);
        } catch (IOException e) {
            logger.warn("Failed to create emoji cache directory, {}", e.getMessage());
        }
    }

    private EmojiUtil() {}

    public static Image toImage(String emoji, int size) {
        String cacheKey = emoji + ":" + size;
        synchronized (memCache) {
            Image cached = memCache.get(cacheKey);
            if (cached != null) {
                return cached;
            }
            Image loaded = load(emoji, size);
            if (loaded != null) {
                memCache.put(cacheKey, loaded);
            }
            return loaded;
        }
    }

    private static Image load(String emoji, int size) {
        String codepoints = toCodepoints(emoji);
        if (codepoints.isBlank()) {
            return null;
        }

        URL bundled = EmojiUtil.class.getResource(RESOURCES_BASE + codepoints + ".png");
        if (bundled != null) {
            return new Image(bundled.toExternalForm(), size, size, true, true, false);
        }

        Path cached = DISK_CACHE.resolve(codepoints + ".png");
        if (Files.exists(cached)) {
            return new Image(cached.toUri().toString(), size, size, true, true, false);
        }

        String url = CDN + codepoints + ".png";
        Image img = new Image(url, size, size, true, true, true);
        downloadToDiskAsync(url, cached);
        return img;
    }

    private static void downloadToDiskAsync(String url, Path dest) {
        UiBackgroundExecutor.get().execute(() -> {
            try {
                byte[] data = URI.create(url).toURL().openStream().readAllBytes();
                Files.write(dest, data);
            } catch (Exception ignored) {}
        });
    }

    private static String toCodepoints(String emoji) {
        if (emoji == null) {
            return "";
        }

        String normalized = emoji.trim();
        if (normalized.isEmpty()) {
            return "";
        }

        // Supports stored formats like "U+1F1FA U+1F1F8" or "1F1FA-1F1F8".
        String tokenized = normalized
                .toUpperCase(Locale.ROOT)
                .replace("U+", "")
                .replace('_', '-')
                .replace(' ', '-')
                .replaceAll("[^0-9A-F-]", "");

        if (tokenized.matches("[0-9A-F]+(?:-[0-9A-F]+)*")) {
            return tokenized.toLowerCase(Locale.ROOT);
        }

        return emoji.codePoints()
                .filter(cp -> cp != 0xFE0F)
                .mapToObj(Integer::toHexString)
                .collect(Collectors.joining("-"));
    }
}
