package com.triplify.ui.shared.util;

import com.google.inject.Inject;
import com.google.inject.Injector;
import com.google.inject.Singleton;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;

import java.io.IOException;
import java.net.URL;

//Generated by Copilot, modified
@Singleton
public final class FxmlLoaderHelper {

    private final Injector injector;

    @Inject
    public FxmlLoaderHelper(Injector injector) {
        this.injector = injector;
    }

    public <N extends Node, C> FxmlLoadResult<N, C> load(String resourcePath) {
        URL url = getClass().getResource(resourcePath);
        if (url == null) throw new IllegalStateException("FXML not found: " + resourcePath);
        return load(url);
    }

    public <N extends Node, C> FxmlLoadResult<N, C> load(URL fxmlUrl) {
        FXMLLoader loader = new FXMLLoader(fxmlUrl);
        loader.setControllerFactory(injector::getInstance);
        try {
            N node = loader.load();
            C controller = loader.getController();
            return new FxmlLoadResult<>(node, controller);
        } catch (IOException e) {
            throw new RuntimeException("Failed to load FXML: " + fxmlUrl, e);
        }
    }

    public <T extends Node> void loadComponent(String resourcePath, T rootController) {
        URL url = rootController.getClass().getResource(resourcePath);
        if (url == null) throw new IllegalStateException("FXML not found: " + resourcePath);
        loadComponent(url, rootController);
    }

    public <T extends Node> void loadComponent(URL fxmlUrl, T rootController) {
        FXMLLoader loader = new FXMLLoader(fxmlUrl);
        loader.setRoot(rootController);
        loader.setController(rootController);
        loader.setControllerFactory(injector::getInstance);
        try {
            loader.load();
        } catch (IOException e) {
            throw new RuntimeException("Failed to load component FXML: " + fxmlUrl, e);
        }
    }
}
