package com.triplify.infrastructure.repository.persistence;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.sqlite.SQLiteConnection;
import com.triplify.domain.util.DefaultDataDirectories;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Collections;
import java.util.List;

// Generated by Copilot
public class SQLiteConnectionFactory {
    private static final Logger logger = LoggerFactory.getLogger(SQLiteConnectionFactory.class);

    private static final String DB_PATH_PROPERTY = "triplify.db.path"; // JVM property key for db path override
    private static final String DB_PATH_ENV = "TRIPLIFY_DB_PATH"; // Env var key for db path override

    private static Connection instance;
    private static boolean spatialiteLoaded = false;

    // Cached extracted bundle so reconnects reuse the same on-disk native files.
    private static NativeBundle extractedBundle;

    // Close SQLiteConnection at shutdown
    static {
        Runtime.getRuntime().addShutdownHook(new Thread(SQLiteConnectionFactory::close));
    }

    private SQLiteConnectionFactory() {
    }

    private record NativeBundle(Path directory, Path mainLibrary) {
    }

    public static synchronized Connection getConnection() {
        try {
            if (instance == null || instance.isClosed() || !instance.isValid(1)) {
                String jdbcUrl = buildJdbcUrl();
                instance = DriverManager.getConnection(jdbcUrl);
                spatialiteLoaded = false;
                enableSpatiaLite(instance);
                logger.debug("SQLite connection established");
            }
            return instance;
        } catch (SQLException e) {
            logger.error("Failed to establish SQLite connection", e);
            throw new RuntimeException(e);
        }
    }

    private static synchronized void close() {
        if (instance != null) {
            try {
                instance.close();
                logger.debug("SQLite connection closed");
            } catch (SQLException e) {
                logger.warn("Failed to close SQLite connection", e);
            } finally {
                instance = null;
            }
        }
    }

    private static void enableSpatiaLite(Connection connection) {
        if (spatialiteLoaded) {
            return;
        }

        try (Statement stmt = connection.createStatement()) {
            SQLiteConnection sqliteConn = connection.unwrap(SQLiteConnection.class);
            sqliteConn.getDatabase().enable_load_extension(true);

            if (extractedBundle == null) {
                extractedBundle = extractLibrary();
            }

            String escapedPath = escapeSqlLiteral(extractedBundle.mainLibrary().toString());
            stmt.execute("SELECT load_extension('" + escapedPath + "')");
            configureProjDatabase(stmt, extractedBundle.directory());

            // Disable extension loading now that SpatiaLite is loaded
            sqliteConn.getDatabase().enable_load_extension(false);

            spatialiteLoaded = true;
            logger.debug("SpatiaLite loaded successfully");
        } catch (Exception e) {
            logger.error("Failed to load SpatiaLite", e);
            throw new RuntimeException("SpatiaLite could not be loaded", e);
        }
    }

    private static String resolvePlatformFolder() {
        String os = System.getProperty("os.name").toLowerCase();
        String arch = normalizeArchitecture(System.getProperty("os.arch"));

        if (os.contains("win")) return "/spatialite/windows-x86-64";
        if (os.contains("mac")) {
            if (arch.equals("arm64")) return "/spatialite/macos-arm64";
            if (arch.equals("x86-64")) return "/spatialite/macos-x86-64";
            throw new RuntimeException("Unsupported macOS architecture: " + arch);
        }
        if (os.contains("linux")) return "/spatialite/linux-x86-64";

        throw new RuntimeException("Unsupported OS/architecture: " + os + "/" + arch);
    }

    private static String resolveLibraryName() {
        String os = System.getProperty("os.name").toLowerCase();

        if (os.contains("win")) return "mod_spatialite.dll";
        if (os.contains("mac")) return "mod_spatialite.dylib";
        if (os.contains("linux")) return "mod_spatialite.so";

        throw new RuntimeException("Unsupported OS: " + os);
    }

    // Windows: dependency DLLs must be pre-loaded via System.load() in topological
    // (leaf-first) order, because Windows does not search the DLL's own directory
    // for its dependencies. mod_spatialite.dll must come last.
    private static final java.util.List<String> WINDOWS_DLL_LOAD_ORDER = java.util.List.of(
            // ── tier 0: no native deps ──
            "zlib1.dll",
            "libwinpthread-1.dll",
            "libgcc_s_seh-1.dll",
            "libstdc++-6.dll",
            // ── tier 1: depend only on tier 0 ──
            "libiconv-2.dll",
            "libtermcap-0.dll",
            "liblzma-5.dll",
            "libexpat-1.dll",
            "libjpeg-62.dll",
            "libzstd.dll",
            "libsharpyuv-0.dll",
            "libsqlite3-0.dll",
            // ── tier 2 ──
            "libreadline8.dll",      // → libtermcap
            "libcrypto-3-x64.dll",   // → base
            "libwebp-7.dll",         // → libsharpyuv
            "libminizip-1.dll",      // → zlib
            "libgeos.dll",           // → libstdc++
            // ── tier 3 ──
            "libssl-3-x64.dll",      // → libcrypto
            "libxml2.dll",           // → libiconv, liblzma, zlib
            "libtiff-6.dll",         // → libjpeg, libzstd, liblzma, zlib
            "libgeos_c.dll",         // → libgeos
            "libfreexl-1.dll",       // → libiconv, libminizip
            // ── tier 4 ──
            "libcurl-4.dll",         // → libssl, libcrypto, zlib, libzstd
            "librttopo-1.dll",       // → libgeos_c
            // ── tier 5 ──
            "libproj_9_2.dll",       // → libcurl, libsqlite3, libtiff
            // ── tier 6 (top) ──
            "mod_spatialite.dll"
    );

    private static final List<String> MACOS_ARM64_REQUIRED_FILES = List.of(
            "mod_spatialite.dylib",
            "libxml2.16.dylib",
            "libminizip.1.dylib",
            "librttopo.1.dylib",
            "libfreexl.1.dylib",
            "libproj.25.dylib",
            "libgeos_c.1.dylib",
            "libgeos.3.14.1.dylib",
            "libtiff.6.dylib",
            "libzstd.1.dylib",
            "liblzma.5.dylib",
            "libjpeg.8.dylib",
            "proj.db"
    );

    // Copies required native libs from resources to temp filesystem
    private static NativeBundle extractLibrary() throws IOException {
        String folder = resolvePlatformFolder();
        String libraryName = resolveLibraryName();

        // Create a single temp directory to hold all platform files
        Path tempDir = Files.createTempDirectory("spatialite");
        tempDir.toFile().deleteOnExit(); // Mark directory for deletion on JVM exit

        // List all resources inside the platform folder using the classpath
        URI folderUri;
        try {
            var resource = SQLiteConnectionFactory.class.getResource(folder);
            if (resource == null) throw new IOException("Resource folder not found on classpath: " + folder);
            folderUri = resource.toURI();
        } catch (URISyntaxException e) {
            throw new IOException("Could not resolve resource folder URI: " + folder, e);
        }

        // Support both plain directories (IDE / exploded) and JARs
        FileSystem jarFs = null; // Will hold temporary filesystem if reading from JAR
        boolean createdJarFs = false; // Track whether we created the filesystem (vs reused)
        Path resourceDir; // Path handle to resource folder
        if (folderUri.getScheme().equals("jar")) { // If running from packaged JAR
            try {
                jarFs = FileSystems.getFileSystem(folderUri); // Reuse already-open JAR filesystem
            } catch (FileSystemNotFoundException e) {
                jarFs = FileSystems.newFileSystem(folderUri, Collections.emptyMap()); // Mount JAR as filesystem
                createdJarFs = true;
            }
            resourceDir = jarFs.getPath(folder); // Get folder path inside mounted JAR FS
        } else {
            resourceDir = Path.of(folderUri);
        }

        // Copy all native library files from classpath resources to a real temp directory,
        // because extension loading/System.load requires filesystem paths (not in-JAR resources)
        try (var stream = Files.list(resourceDir)) {
            for (Path entry : stream.toList()) {
                String fileName = entry.getFileName().toString();
                Path dest = tempDir.resolve(fileName);
                try (var in = SQLiteConnectionFactory.class.getResourceAsStream(folder + "/" + fileName)) {
                    if (in == null) continue;
                    Files.copy(in, dest, StandardCopyOption.REPLACE_EXISTING);
                    dest.toFile().deleteOnExit();
                }
            }
        } finally {
            // Only close the JAR filesystem if we created it — closing a shared one
            // would break other code still reading from the JAR.
            if (createdJarFs && jarFs != null) jarFs.close();
        }

        // On Windows, pre-load each DLL in dependency order via System.load()
        // so the JVM's loaded-library table satisfies all transitive dependencies
        // when mod_spatialite.dll is later loaded by SQLite's load_extension.
        String os = System.getProperty("os.name").toLowerCase();
        if (os.contains("win")) {
            for (String dll : WINDOWS_DLL_LOAD_ORDER) {
                Path dllPath = tempDir.resolve(dll);
                if (Files.exists(dllPath)) {
                    System.load(dllPath.toAbsolutePath().toString());
                    logger.debug("Pre-loaded Windows DLL: {}", dll);
                }
            }
        }

        validateBundleContents(folder, tempDir);
        Path mainLibrary = tempDir.resolve(libraryName).toAbsolutePath();
        logger.debug("Prepared SpatiaLite bundle for {} at {}", folder, tempDir);
        return new NativeBundle(tempDir, mainLibrary);
    }

    private static void validateBundleContents(String folder, Path extractedDir) throws IOException {
        List<String> requiredFiles = switch (folder) {
            case "/spatialite/macos-arm64" -> MACOS_ARM64_REQUIRED_FILES;
            default -> List.of();
        };

        for (String file : requiredFiles) {
            Path path = extractedDir.resolve(file);
            if (!Files.exists(path)) {
                throw new IOException("Missing required SpatiaLite bundle file: " + path);
            }
        }
    }

    private static void configureProjDatabase(Statement stmt, Path extractedDir) throws SQLException {
        Path projDbPath = extractedDir.resolve("proj.db");
        if (!Files.exists(projDbPath)) {
            logger.debug("No bundled proj.db found in {}", extractedDir);
            return;
        }

        String escapedPath = escapeSqlLiteral(projDbPath.toAbsolutePath().toString());
        stmt.execute("SELECT PROJ_SetDatabasePath('" + escapedPath + "')");
        logger.debug("Configured bundled PROJ database path: {}", projDbPath);
    }

    private static String normalizeArchitecture(String arch) {
        if (arch == null) {
            return "unknown";
        }

        return switch (arch.toLowerCase()) {
            case "aarch64", "arm64" -> "arm64";
            case "x86_64", "amd64" -> "x86-64";
            default -> arch.toLowerCase();
        };
    }

    private static String escapeSqlLiteral(String value) {
        return value.replace("'", "''").replace("\\", "\\\\");
    }

    private static String buildJdbcUrl() {
        Path dbPath = resolveDbPath().toAbsolutePath().normalize();
        logger.debug("Using database path: {}", dbPath);
        try {
            // Ensure all missing parent directories for the database path exist, creating them if needed
            Path parent = dbPath.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
        } catch (IOException e) {
            throw new RuntimeException("Failed to create SQLite parent directory: " + dbPath, e);
        }
        return "jdbc:sqlite:" + dbPath;
    }

    private static Path resolveDbPath() {
        String configuredPath = System.getProperty(DB_PATH_PROPERTY);
        if (configuredPath == null || configuredPath.isBlank()) {
            configuredPath = System.getenv(DB_PATH_ENV);
        }

        if (configuredPath != null && !configuredPath.isBlank()) {
            return Path.of(configuredPath.trim());
        }

        return DefaultDataDirectories.resolve("Triplify").resolve("triplify.db");
    }
}
